version: 'sodms-mailer'

services:
  db:
    image: mysql:5.7
    container_name: sodms-mailer-db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sodms-net
  redis:
    image: redis:3-alpine
    container_name: sodms-mailer-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sodms-net

  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    container_name: sodms-mailer-web
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    stdin_open: true
    tty: true
    networks:
      - sodms-net

  worker:
    build: .
    container_name: sodms-mailer-worker
    command: bundle exec rake environment resque:work QUEUE=*
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - sodms-net

  scheduler:
    build: .
    container_name: sodms-mailer-scheduler
    command: bundle exec rake resque:scheduler
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - sodms-net

volumes:
  mysql_data:
  redis_data:
  bundle_cache:

networks:
  sodms-net:
    external: true