SODMS_BACKEND_BASE: 'http://203.202.249.100:8070'
IWCT_BACKEND_BASE: 'http://175.29.189.243:8070'
ISATL_BACKEND_BASE: 'http://103.4.65.211:8070'
SODMS_BACKEND_BASE_LOCAL_IP: 'http://192.168.0.8:8070'
LOCAL_BACKEND_BASE: 'http://localhost:5000'
EmptyContainerCC: 'csdreportinglist@saplbd.com'
ImportContainerCC: 'csdreportinglist@saplbd.com'
CargoStatusCC: 'cfsreportinglist@saplbd.com'
DefaultFrom: 'reporting@saplbd.com'
