SODMS_BACKEND_BASE: 'http://203.202.249.100:8070'
IWCT_BACKEND_BASE: 'http://175.29.189.243:8070'
ISATL_BACKEND_BASE: 'http://103.4.65.211:8070'
SODMS_BACKEND_BASE_LOCAL_IP: 'http://192.168.0.11:8070'
LOCAL_BACKEND_BASE: 'http://localhost:5000'
secret_key_base: f7670a2e2e532da7725724b15b1cdf1a82b9d4a4d85ba08931928de60e66602bbb4ae35240667d8b4ee260f5e91a97ab215adc7b75ded4a894eee9e1365b7b32
EmptyContainerCC: 'csdreportinglist@saplbd.com'
ImportContainerCC: 'csdreportinglist@saplbd.com'
CargoStatusCC: 'cfsreportinglist@saplbd.com'
DefaultFrom: 'reporting@saplbd.com'